name: Deploy Dynamic

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm build
      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: hfunctions
          slot-name: Production
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CAF1542826994EF0A154557AA79ACED7 }}
